### ISSUE TITLE
Instructions for OCICL

### ISSUE THREAD

**Issue by Immortalin** [rabbibotton/clog#360] opened 2024-05-28 18:36 UTC
Most of the tutorial and documentation assumes the presence of quicklisp. Would you mind adding the equivalent commands for an Ocicl based system?

**Comment by rabbibotton** [comment] 2024-05-28 19:06
Is for sure planned, will try and bump it up on schedule

**Comment by rabbibotton** [comment] 2024-07-07 22:53
Worked today on this, the issue is that the builder uses QuickLisp to retrieve the list of project available. OCICL that is not a concept that really jives as each project is its own "world". It is possible to offer an alternative model that is more "file based" and then "system" based as QL is. I will work on that.

In the mean time worth positing my notes here so far:

1. Fresh install of sbcl - or mv ~/.sbclrc ~/.sblrc.org  you also want to make sure no conflicts in ~/common-lisp if using it
2. git clone https://github.com/ocicl/ocicl.git
3. sbcl --load setup.lisp
4. edit .sbclrc with

;; Add the following to your lisp startup file
;; (~/.sbclrc, ~/.eclrc, ~/.abclrc or ~/.roswell/init.lisp):

#-ocicl
(when (probe-file #P"/home/dbotton/.local/share/ocicl/ocicl-runtime.lisp")
  (load #P"/home/dbotton/.local/share/ocicl/ocicl-runtime.lisp"))
(push (uiop:getcwd) asdf:*central-registry*)

5. export PATH="~/.local/bin/:$PATH"   if not already exported
6. Copy your CLOG project to compile to a directory
7. cd to that dir then
8. (pushnew (uiop:getcwd) asdf:*central-registry*)
9. (asdf:load-system :ntest) ; ntest what ever name of projects is
10. run your compiled project - for example (ntest:start-app)

ideally I should be able to do:

11. (asdf:load-system :ntest/tools)
12. (clog-tools:clog-builder :project :ntest)

Also for some reason the install CLOG is a very old version

**Comment by rabbibotton** [comment] 2024-07-07 22:55
clog that was installed was from clog-20240503-76468c7/
in CLOG time that is 50 years :)

**Comment by aykaramba** [comment] 2024-07-08 00:52
Interesting.  I have been meaning to learn OCICL, I will try this a bit also.  Thx for the nfo.

**Comment by rabbibotton** [comment] 2024-07-08 01:21
Once we figure what is broke with versions, I already implemented:
(clog-tools:clog-builder :project :ntest :no-quicklisp t)

**Comment by rabbibotton** [comment] 2024-07-08 10:17
So things were fixed on the server end so instructions work now.

Do: ocicl latest
To update if already did

Will work today on official Docs

**Comment by rabbibotton** [comment] 2024-07-08 18:49
CLOG now supports non-quicklisp based development completely based off of ASDF. This allows for OCICL based systems see https://github.com/rabbibotton/clog/blob/main/OCICL.md

**Closed by rabbibotton** 2024-07-08 18:49 UTC

**Comment by rabbibotton** [comment] 2024-07-08 19:06
You will though have to wait for CLOG to update in ocicl not sure what the deal is there https://github.com/ocicl/clog?tab=readme-ov-file
