### ISSUE TITLE
Rendering issues with clogpower.com

### ISSUE THREAD

**Issue by mustiboost** [rabbibotton/clog#204] opened 2022-08-07 20:24 UTC
I recorded a gif to show you what happens on Edge and Chrome when going to clogpower.com and clicking on "demo": 

https://imgur.com/a/xkjkJbI

Issues: 

1. Entire screen is moving instead of just the "airship car".  
2. After the menu appears (after clicking on center circle) and clicking on any link and then hitting the "back" button on the browser, the airship does not move anymore. Need to hit "refresh" to make it start moving again. On Safari you don't even see the animation screen, just the menu screen with the links when hitting "back".  Maybe that's what you originally intended to happen. 

Funny enough Chrome on Mac and Firefox on Windows do not have the "whole screen jumping" issue at all. But, the "back button" issue is still there. Same with Firefox on Mac. I'll have to test the browsers on Linux later and will report back.

**Comment by aykaramba** [comment] 2022-08-07 20:47
That just looks like the scroll bar is being triggered.

**Comment by mustiboost** [comment] 2022-08-07 20:58
I think you're right. They question is "why?" Must be windows-chrome specific since it only occurs on chrome/edge(which is basically chrome) on windows.

**Comment by mustiboost** [comment] 2022-08-07 21:23
I also just noticed that after hitting the "back" button to get back to "demo", all functionality is gone (not just the animation) before hitting the "refresh" button. I.e. when you click on the center circle, nothing happens. No menus come up.  This happens after hitting the "forward" button too, i.e. after going to "demo" you click on the center circle to bring up the menu, then hit the back button to go to the main clogpower.com page, then hit "forward" to get back to the demo. All functionality is gone.    If you immediately hit the "back" button after going to "demo" (without clicking the circle and bringing up the menu) and then hit "forward" everything works fine still. Again, on Safari everything works fine no matter what. :)

**Comment by rabbibotton** [comment] 2022-08-07 21:25
mustiboost - what platform? I am not seeing it on chrome or firefox on Mac

**Comment by mustiboost** [comment] 2022-08-07 21:31
Windows and mac so far, need to test on linux still. If you have trouble replicating the issue, just open a completely new chrome/firefox window and go to clogpower.com, not just a tab. Tabs have inconsistent behavior sometimes.

**Comment by rabbibotton** [comment] 2022-08-08 02:24
I am not likely going to get to this for a bit, but will.

**Comment by aykaramba** [comment] 2022-08-08 03:17
Maybe we can track this one down.  Not terribly important.

**Comment by mustiboost** [comment] 2022-08-08 05:11
No problem, David.  @aykaramba  I completely disagree. These things are *very* important. If I'm an individual or a company that is curious about CLOG but the frontend has obvious bugs when I look at the demo on its own website, then I'm not going to pick it for my project, no matter how ingenious possibly the lisp part is. CLOG is not just lisp, but a combination of lisp, javascript, html and css.  As fun as we think writing software is, we still want people to use it. The more, the better. So it is *terribly* important.  However, as you alluded to, this one should not be that hard to fix given time as html/css and javascript are so omnipresent and we're not the first people to have run into browser inconsistencies.

**Comment by aykaramba** [comment] 2022-08-08 05:19
How about we stop wasting the Rabbis precious time on trivialities and talent on trivialities that we can fix?  

My self, I am learning Common Lisp + CLOG to help with the following:

1) Build a couple of tutorials that I am interested in.

2) Build a theming application that shows all the widgets, lets you style them up and shows you how to create sophisticated layouts with W3.css

3) go through all the tutorials on google docs and do a bit of spot editing and update all the images to reflect the latest CLOG Builder.

How about you track it down and fix it?

**Comment by mustiboost** [comment] 2022-08-08 06:09
> How about we stop wasting the Rabbis precious time on trivialities for items we can fix?

--So, when you don't know how to respond you start lashing out?  

> How about you track it down and fix it?

--Don't worry, I'm doing my part as we speak. Also, you're saying..."unless you're willing to fix it, don't even post a new issue/bug, because you're wasting David's time!"?  Wow....  

Having said that, I appreciate your enthusiasm and willingness to help, but I'm not sure if it's necessarily the best idea for a Lisp newbie (or maybe even programming newie) to write tutorials....or comment on what's "trivial" or "terribly important". 

With that out of the way, can we now stop this nonsense and not pollute this issue with non-relevant chest thumping and finger pointing ("I am doing this and that...what are YOU doing? You should be doing this and that")? I'll only be replying to relevant posts from now on and will ignore the rest.

**Comment by aykaramba** [comment] 2022-08-08 06:19
You know what could use a tutorial?  The new project tools in builder.  They are amazing.  Why don't you write a tutorial on that after you are done tracking down why a div is 1 pixel over whatever the chrome render engine believes is outside its window bounds?  Honestly, it's probably a trivial issue.

Also, give this thread a day or so and come back and read it again.  You are severely misreading text for what it isn't.

**Comment by rabbibotton** [comment] 2022-08-08 11:45
On Mon, Aug 8, 2022 at 1:11 AM mustiboost ***@***.***> wrote:

> No problem, David. @aykaramba <https://github.com/aykaramba> I completely
> disagree. These things are *very* important.
>
I agree, my intention was that normal turn around of a day maybe a week
simply because the issue is in the demo itself and likely a stupid error on
my part not in CLOG.

If I'm an individual or a company that is curious about CLOG but the
> frontend has obvious bugs when I look at the demo on its own website, then
> I'm not going to pick it for my project, no matter how ingenious possibly
> the lisp part is.
>
Agreed.


> CLOG is not just lisp, but a combination of lisp, javascript, html and
> css. As fun as we think writing software is, we still want people to use
> it. The more, the better. So it is *terribly* important. However, as you
> alluded to, this one should not be that hard to fix given time as html/css
> and javascript are so omnipresent and we're not the first people to have
> run into browser inconsistencies.
>
Agreed

**Comment by rabbibotton** [comment] 2022-08-08 11:52
> How about we stop wasting the Rabbis precious time on trivialities and
> talent on trivialities that we can fix?
>

 It is never a waste of time. In fact the early questions and issues are
important to see and deal with. It is not just the bug I look at but _why_
I missed it.

<<How about you track it down and fix it?>>

I am super happy that I have great people like yourself willing to help and
an incredible range of interest from hardened long time Lisp hackers to
newbies in CLOG, I don't expect anyone to fix things especially till they
are using CLOG and have learned about why this technique is sp
revolutionizing for web apps. It has some small clinks left in "web pages"
and will get to them as they come up (once a person uses CLOG for awhile
they change how they think about the web and they write apps even for
"websites")/

**Comment by rabbibotton** [comment] 2022-08-08 13:46
btw, I do thank you though for watchin' my back :) and very very much for
wanting to track his down. I am overall thrilled that so many want to get
involved and happy they do.

**Comment by mustiboost** [comment] 2022-08-08 15:46
> I agree, my intention was that normal turn around of a day maybe a week simply because the issue is in the demo itself and likely a stupid error on my part not in CLOG. 

--Got it, no problem at all of course! 👍

**Comment by rabbibotton** [comment] 2022-08-19 01:42
For 1 I cannot reproduce the errors so far on windows or mac
For 2 it is a caching issue. It should be possible to induce the browser to not cache or restart the connection. I will look more in to it tomorrow.

**Comment by mustiboost** [comment] 2022-08-20 21:44
1 only happens on Windows in Edge and Chrome, and only when in full screen mode. In Edge it does not happen if the "sidebar" is visible on the right (Ctrl+Shift+/). On Chrome on the Mac it does not happen. Let me know if you can reproduce now.

**Comment by aykaramba** [comment] 2022-08-20 23:14
I have now tested this on windows 7, 8.1, 10 and 11.  Details:

1) Edge - full screen mode - no rendering issues at all.

2) Chrome - full screen mode - no rendering issues at all.

I don't see the problem on any windows machine that I try.

**Comment by rabbibotton** [comment] 2022-11-20 21:10
I plan on redoing clogpower in January, so going to close this for now.

**Closed by rabbibotton** 2022-11-20 21:10 UTC
