### ISSUE TITLE
installation via OCICL

### ISSUE THREAD

**Issue by MarcRohrer** [rabbibotton/clog#343] opened 2024-04-21 16:25 UTC
Hi,

I tried to installed CLOG on Windows via OCICL, but:

```
H:\src>mkdir clog

H:\src>cd clog

H:\src\clog>ocicl install clog
; downloaded ghcr.io/ocicl/clog@sha256:9f3415c31dac331b896b4fb06f7c640ce5bfea69d4d2ac7e0f45876945644732
; downloaded ghcr.io/ocicl/clack@sha256:74657e323ad402af72f5eb2b668035539f687502606c47b880f76f9b38d7d325
; downloaded ghcr.io/ocicl/lack@sha256:1224e0d4ecb16655b8b2f2469aa04cc6e0a8db533cbc654bd07b7c5856da8d6e
; downloaded ghcr.io/ocicl/ironclad@sha256:06ecd2ec5c41c61cce6788adde6a8e56b6002764042002d9ff13308c998fffdd
; downloaded ghcr.io/ocicl/bordeaux-threads@sha256:9df017ccbb783949cdaea6c7849d678105e041b784d0fc738220873739c3bfe5
; downloaded ghcr.io/ocicl/alexandria@sha256:2204779a9711f65532863abc61e9644c2a5a6839c4544516f19d04b699af8a7a
; downloaded ghcr.io/ocicl/global-vars@sha256:22937c8bd0f635855c2c044b0ae0ab3b438ba5e858192dae462807148547d99a
; downloaded ghcr.io/ocicl/trivial-features@sha256:9da86d54aeabcaeb43e69e0a1d6d04c42d9446f2094c8752d89d4ca6ba1b7cbd
; downloaded ghcr.io/ocicl/trivial-garbage@sha256:fdcc5b6acd3eacb1e9ee305685b72ea270435cf363ea7a9cb1cc3d86a3534ed7
; downloaded ghcr.io/ocicl/usocket@sha256:e8f5862adc7ac2a5e9d25cf01e63cdffde2a1c553379d91aa2ad3dad0ad3c491
; downloaded ghcr.io/ocicl/split-sequence@sha256:e3883aa62ed7def931505d24f3cde4ab47d4a715cebf32de90615b8dad292bac
; downloaded ghcr.io/ocicl/swank@sha256:a280fabc40b8394ab39562846887a335a165118e7765b6721e1b74529791630f
; downloaded ghcr.io/ocicl/websocket-driver@sha256:ce9e8e42c375b013d6ed18b15f20c2b53fd91683f9548165814cb385de7978fd
; downloaded ghcr.io/ocicl/fast-websocket@sha256:0bdb0f14542d60ab48f435abb5f39a858de4b7285b1209871dbdff7227727977
; downloaded ghcr.io/ocicl/fast-io@sha256:d5907b55d2d46cfe6a811e560faf487b6cdf150c0074fe3557438a2143744998
; downloaded ghcr.io/ocicl/trivial-gray-streams@sha256:e732a802d3207ac012d4ffdcf18f3a2bcbf2e625c00b6a90ca5ea861c858bb32
; downloaded ghcr.io/ocicl/static-vectors@sha256:54e113712b9f3ca0c5809b6769812bfda1a59cc3094575385856a17c5c2eb246
; downloaded ghcr.io/ocicl/cffi@sha256:b6f93e6cfd73fb3e9dd33474fb81760a5fe3617cc32cff8811d8a3e3769a360d
; downloaded ghcr.io/ocicl/babel@sha256:beda9fd8bec204f077596f8d91b819dba31444dfec7a670575ca6055a9dbfabb
; downloaded ghcr.io/ocicl/event-emitter@sha256:888209116a90ef9a97c4d401e94428e798da3daf7d30d7d0d6d8ac32624fe87a
; downloaded ghcr.io/ocicl/sha1@sha256:4ee91733ee872864c804d29dbdf417b7fbacf489e8c5e71f047f76499777adb7
; downloaded ghcr.io/ocicl/cl-base64@sha256:a88846138b190a3a4a7082e44f360236faccb9f545cd38b7b12ae07eae292e3d
; downloaded ghcr.io/ocicl/cl_plus_ssl@sha256:28052d1112e5d42d38ea01cda70cfa122bc361dedd720d8fdb5cd409e0e41459
; downloaded ghcr.io/ocicl/flexi-streams@sha256:2eb7271c30799a51bb3720ca37ee358764522255d66aabcc1a3012becfab1dbc
; downloaded ghcr.io/ocicl/fast-http@sha256:1f2532bd45c68ed5ff7e7f2876c59c823aeff31044826b055a46ffa18752cdc6
; downloaded ghcr.io/ocicl/cl-utilities@sha256:e3f78ec41bc5024050c11772fcfb6b773eade4c002b9260a7d16a76d098cea42
; downloaded ghcr.io/ocicl/proc-parse@sha256:19dad8a437f8885b91a5939aef5ea691aa19225eaf3ad4616e58d3898dd12a5d
; downloaded ghcr.io/ocicl/xsubseq@sha256:bd2fd7822275156ad788c6e3d67b519f69b85fcc800fe5798184281cd127e45a
; downloaded ghcr.io/ocicl/smart-buffer@sha256:0a6e068b34b9be33f3a3c996cf31453ac68acd82b7deff7c4827e8fc6b4cd18d
; downloaded ghcr.io/ocicl/quri@sha256:3d3c62bb4e3da80c7d9c6829010e0f4a223ab3fe13b31dd1821b352f04d24909
; downloaded ghcr.io/ocicl/hunchentoot@sha256:50dd44b1aa49c24047bb86271238ee816c3b65d45589b9e90c9dfb26f28eae11
; downloaded ghcr.io/ocicl/chunga@sha256:5f99909890ba5bf2a725e6de75baab3fff3750d4bf2818f9f0b46c4eeed98703
; downloaded ghcr.io/ocicl/cl-fad@sha256:4abd6537a2e7115b20dbe46c7e6656923f42686d78820d42ed54d6833b6410fc
; downloaded ghcr.io/ocicl/cl-ppcre@sha256:da286c491967b814862b089d16f51d54ed6412e51f4fccb5a479cef5f41a1849
; downloaded ghcr.io/ocicl/md5@sha256:00e8b92eea99b82a75eac0e359316bdd532f3aa076a24ba27e8e1958790c5447
; downloaded ghcr.io/ocicl/rfc2388@sha256:6fe862d7c4bb7553b9a4372c5ca97cba2c2582c134aef921f9434db5b0cc024c
; downloaded ghcr.io/ocicl/trivial-backtrace@sha256:8189c3a641490b523a67b6711bdf44a2b4b64e2c51604cf991247d9353597d21
; downloaded ghcr.io/ocicl/trivial-open-browser@sha256:47f53f7a4d0a94292570a1f777fd8437e1ae7a173f8e43469f625f877f289622
; downloaded ghcr.io/ocicl/parse-float@sha256:ac97572fb76ce4512e43399ac40f8c7f56e75bcd86e2eb080d3cc501fe22e17c
; downloaded ghcr.io/ocicl/trivial-mimes@sha256:5b7f32f90f94fb73cde2e7d1f2a941fe5ee1a3d22b316e6837303e6efe07a28a
; downloaded ghcr.io/ocicl/trivial-rfc-1123@sha256:0c3d00e8cd13b7c325fcff3a1ed912a60c7a3ee8f06f94265e4d01a2a0b72278
; downloaded ghcr.io/ocicl/http-body@sha256:6cf92164a536aed3a16b532d067b47f2bf9dc57751b82a690dbd79e9598e967e
; downloaded ghcr.io/ocicl/jonathan@sha256:1ba63deac3ec7b9c7b51b8610d731922534463e641659c28eb0568ee59e76d43
; downloaded ghcr.io/ocicl/cl-syntax@sha256:980cfae2c3e546b18199849b39f922134b6053b4455ee3804d8cc49f92021bbd
; downloaded ghcr.io/ocicl/trivial-types@sha256:441b53889ea0479df78424dca18172d4a67f7c816b56163c884e1e0bc74be4d7
; downloaded ghcr.io/ocicl/named-readtables@sha256:c13ae35d957cf55f8c877762a24537daee5e8322d9968b14f8c86e8cfc1b2df3
; downloaded ghcr.io/ocicl/cl-annot@sha256:611a41daa8943d3a6c29c21b1ebf8459d70fc69ccc73203b6fa58bf333901bed
; downloaded ghcr.io/ocicl/circular-streams@sha256:1ed2c55b357f47a92d43e8158615f7220f0998cac73c729b63b4d6a4b480923b
; downloaded ghcr.io/ocicl/closer-mop@sha256:41002bac33411683ab917153091aa9bea7c01a6abf9b869252e89d64f36a4546
; downloaded ghcr.io/ocicl/mgl-pax@sha256:3a5c4c409f126728c09156fd6eafaa3a80aa1804d82fe777937f7ab72e3e13cb
; downloaded ghcr.io/ocicl/pythonic-string-reader@sha256:a4474310196c2f3e724f42f90ffe15387b03d587e7b4e224e2873d8f321136b3
; downloaded ghcr.io/ocicl/cl-template@sha256:2996b5710a1bc413902fc3f4026aad051e40472f24e929feb058d2454059d650
; downloaded ghcr.io/ocicl/atomics@sha256:7e8c10a6aa9c075752458084e77ace432808ac144429c8e862a0b049639c5efc
; downloaded ghcr.io/ocicl/documentation-utils@sha256:b2a1b3f3bcd1a738af85ae2b0168d408c177661eab6d6bbebb254e394d983f54
; downloaded ghcr.io/ocicl/trivial-indent@sha256:6fe5b8470816a715113c0f123d41d52fc2782309fd5fc33a494dd887c6c677ce
; downloaded ghcr.io/ocicl/sqlite@sha256:2742f8c3ff9fb2bf463fe176da1dab28106b030a3f15fb4b79d2dd5891b0b89e
; downloaded ghcr.io/ocicl/iterate@sha256:b605c6d0144892db02c4fc50094b4f854813b0daac54c840f15ba0e921283851
; downloaded ghcr.io/ocicl/cl-dbi@sha256:eec4b0ac8b794db6e51ae034008e667e577c88278ee104eab1a8cfdfc01b5c0b
; downloaded ghcr.io/ocicl/cl-pass@sha256:1b407ad304da67555a83d7f0a81e0f7528c9e31b39fbaa0839080357ab30c489
; downloaded ghcr.io/ocicl/trivial-utf-8@sha256:6ad4c3d48f37cc4eb7a1af18399e8d3f3c506b682ab9498c93130dd3dae1ce1c
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Package CL-ISAAC does not exist.
;
;       Line: 98, Column: 22, File-Position: 3853
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file H:\\src\\clog\\systems\\lack-20240202-c09ef66\\src\\util.lisp" {100440D153}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10013C0073}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "lack-util" "src/util">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "lack-util" "src/util">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "lack-util" "src/util">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Exit from the current thread.

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "lack-util" "src/util">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0]
```
The OCICL maintainer Anthony Green says:

This is a bug in lack-util. cl-isaac is not supported on Windows, and yet the cl-isaac package is referenced unconditionally in lack-util.
```
defsystem "lack-util"
  :version "0.2.0"
  :author "Eitaro Fukamachi"
  :license "MIT"
  :depends-on ((:feature (:or :windows :mswindows :win32 :cormanlisp) "ironclad")
               (:feature (:not (:or :windows :mswindows :win32 :cormanlisp)) "cl-isaac")
               "bordeaux-threads")
  :components ((:file "src/util"))
  :in-order-to ((test-op (test-op "t-lack-util"))))
```
But then in util.lisp:

```
;; Patch to fix bug in cl-isaac.
;; When PR is accepted in cl-isaac, the code below can be removed

(defun cl-isaac:rand32 (ctx)
  ;;(declare (optimize (speed 3) (safety 0)))
  (cond
    ((zerop (cl-isaac::isaac-ctx-randcnt ctx))
     (cl-isaac::generate-next-isaac-block ctx)
     (setf (cl-isaac::isaac-ctx-randcnt ctx) 255)
     (aref (cl-isaac::isaac-ctx-randrsl ctx) 255))
    (t
     (aref (cl-isaac::isaac-ctx-randrsl ctx)
           (decf (cl-isaac::isaac-ctx-randcnt ctx))))))
```

Marc Rohrer

**Comment by rabbibotton** [comment] 2024-04-21 16:40
when I manually build on windows from command line I just quickload cl-isaac and then after build clog, it seems to work in slime likely already loaded there, happy you found the cause. Let me know when you fix is included in lack and will remove from my clogez-win64 distro of clog

**Comment by MarcRohrer** [comment] 2024-04-21 17:28
Sorry, misunderstanding here!
I have no association with any of the libraries you use!
I just wanted to let you know, that there is a problem.

**Comment by rabbibotton** [comment] 2024-04-21 17:36
I know :)
I happen to have run into this many times and am really happy to
understand why now and why my work around to pre-load cl-isaac needed.

**Comment by MarcRohrer** [comment] 2024-04-21 17:55
Perfect!So probably the best approach would be, you contact the creator of that library 🌝I do not even know what it is all about 😳

**Comment by rabbibotton** [comment] 2024-04-21 17:58
https://github.com/fukamachi/lack/issues/83

lol thought that was yours :) someone already added it and I subscribed to issue and gave same work around for now.

**Comment by MarcRohrer** [comment] 2024-04-21 18:18
🌝

**Closed** 2024-04-22 12:59 UTC
